#!/usr/bin/env python

import argparse
import os
import sys
from dataclasses import dataclass
from typing import Union


class Fail(Exception):
    pass


@dataclass
class ExtractArchiveResult:
    finaldir: str
    filecount: int


@dataclass
class ParsedPath:
    extension: str
    basepath: str
    extract_command: str
    basedir: str
    abspath: str


def scantree(path, follow_symlinks=False):
    for entry in os.scandir(path):
        if entry.is_dir(follow_symlinks=follow_symlinks):
            yield from scantree(entry.path, follow_symlinks=follow_symlinks)
        else:
            yield entry


# Returns paths sorted in ascending time (oldest first)
def scantree_mtime(path):
    entries = list(scantree(path))
    return sorted(entries, key=lambda x: x.stat().st_mtime)


def parse_path(path) -> Union[ParsedPath, None]:
    m = {
        ".zip": "unzip",
        ".tar": "tar xf",
        ".tar.bz2": "tar xf",
        ".tar.gz": "tar xf",
        ".rar": "unrar x",
        ".7z": "7z x",
        ".7zip": "7z x",
    }

    for ext, cmd in m.items():
        if path.endswith(ext):
            return ParsedPath(extension=ext, extract_command=cmd,
                              basepath=os.path.basename(path).rstrip(ext),
                              basedir=os.path.dirname(os.path.abspath(path)),
                              abspath=os.path.abspath(path))
    return None


def extract_archive(path) -> ExtractArchiveResult:
    parsed = parse_path(path)
    print(parsed)
    return ExtractArchiveResult(finaldir="TODO", filecount=0)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('files', nargs='+', help='archive files to extract')
    parser.add_argument('--verbose', default=False, action='store_true', help='show more detailed messages')
    return parser.parse_args()


def main():
    for path in ARGS.files:
        result = extract_archive(path)
        print(f"{path} -> {result.finaldir} [{result.filecount} files]")


if __name__ == '__main__':
    try:
        ARGS = parse_args()
        main()
    except Fail as f:
        print(*f.args, file=sys.stderr)
        sys.exit(1)
    except KeyboardInterrupt:
        print("Ctrl+C")
